---
- apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- apt_repository: 
    repo: 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main'
    mode: 0644
    state: present

- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: Slack Install packages
  apt:
    pkg: "slack-desktop"
    state: present
